# this yaml is the simplest mode to deploy doris with fe and be.
# the log and be storage use `EmptyDir` mode as disk. when the pod restart the log and storage will lost.
# This yaml only for experience deploy and usability on k8s about doris.
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster
spec:
  feSpec:
    replicas: 1
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 4
      memory: 8Gi
    image: selectdb/doris.fe-ubuntu:2.1.1
  beSpec:
    replicas: 1
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 4
      memory: 8Gi
    image: selectdb/doris.be-ubuntu:2.1.1