version: '3.1'
services:
  olap:
    restart: always
    image: bitnami/clickhouse:23.4.2
    env_file: .env
    volumes:
      - ./persistence/olap:/bitnami/clickhouse
      - ./migrations/olap:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
      - "9000:9000"

  oltp:
    restart: always
    image: bitnami/postgresql:14.8.0
    env_file: .env
    volumes:
      - ./persistence/oltp:/bitnami/postgresql
    ports:
      - "5432:5432"


  zookeeper:
    image: bitnami/zookeeper:3.8
    env_file: .env
    ports:
      - "2181:2181"

  kafka:
    restart: always
    image: bitnami/kafka:3.4
    env_file: .env
    ports:
      - "9092:9092"
#    volumes:
#      - ./persistence/kafka:/bitnami/kafka
    depends_on:
      - zookeeper

  redis:
    restart: always
    image: bitnami/redis:7.0
    env_file: .env
    ports:
      - "6379:6379"

  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
#    volumes:
#      - ./migrations:/fast/migrations
#      - ./logs:/fast/logs
    ports:
      - "8000:8000"
    command: "/bin/bash -c 'source ./initDB.sh && uvicorn start:app'"
