version: '3.1'
services:
  clickhouse:
    restart: always
    image: bitnami/clickhouse:23.4.2
    env_file: .env
    volumes:
      - ./data/migration:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - backend  # 需要backend先执行了initDB.sh把迁移目录拷贝出来，如果宿主机有了则可以不依赖

  postgres:
    restart: always
    image: bitnami/postgresql:14.8.0
    env_file: .env
    ports:
      - "5432:5432"

  kafka:
    restart: always
    image: bitnami/kafka:3.4
    env_file: .env
    ports:
      - "9092:9092"
      - "9093:9093"

  redis:
    restart: always
    image: bitnami/redis:7.0
    env_file: .env
    ports:
      - "6379:6379"

  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres  # initDB.sh需要初始化数据库
